version: '3'

services:
  app:
    image: pddo/cms_demo
    build: .
    command: "bin/start_app"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: pg10
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres

  ssh:
    image: pddo/cms_demo
    command: ["/usr/sbin/sshd", "-D"]
    volumes:
      - .:/app
    ports:
      - "999:22"
    environment:
      DB_HOST: pg10
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres

  pg10:
    image: postgres:10-alpine
    restart: on-failure:5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg10data:/var/lib/postgresql/data

volumes:
  pg10data:
