version: '3'

services:
  app:
    image: pddo/cms_demo
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    environment:
      DB_HOST: pg10-3.cms-demo
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
    logging:
      driver: awslogs
      options:
        awslogs-group: cms_demo
        awslogs-region: ap-southeast-1
        awslogs-stream-prefix: app
